dist: xenial
language: python
python:
    - "3.7"
install:
    - pip install pipenv
    - pipenv install --skip-lock
    - pipenv install coverage==4.0.3 model-mommy==1.6.0 python-coveralls==2.9.1 --skip-lock
script:
    - coverage run manage.py test
after_success:
    - coveralls