# Generated by Django 2.0.5 on 2018-05-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockaccount',
            name='identify',
            field=models.CharField(default='chidimma', max_length=12),
            preserve_default=False,
        ),
    ]
