# Generated by Django 2.0.5 on 2018-05-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeys',
            name='private_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='public_key',
            field=models.TextField(),
        ),
    ]
