# Generated by Django 2.0.5 on 2018-05-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_blockaccount_identify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockaccount',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='blockaccount',
            name='used',
            field=models.FloatField(default=0.0),
        ),
    ]
