# Generated by Django 2.0.5 on 2018-05-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0001_initial'),
        ('chain', '0002_auto_20180529_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserKeys',
            new_name='BlockAccount',
        ),
    ]
