# Generated by Django 2.0.5 on 2018-05-29 11:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0003_auto_20180529_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockaccount',
            name='initial',
        ),
        migrations.AddField(
            model_name='blockaccount',
            name='used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
