# Generated by Django 2.0.5 on 2018-05-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0004_auto_20180530_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockaccount',
            name='alias',
            field=models.CharField(max_length=30),
        ),
    ]
